
const sampledb = "[{\"key\":\"lbrph1fx\",\"title\":\"Somethig\"},{\"key\":\"lbrphexm\",\"title\":\"LorenIPsum\",\"children\":[{\"key\":\"lbrpu3fn\",\"title\":\"child node\"}]}]"

const samplenode = {
    "lbros266": "",
    "lbrpu3fn": "<blockquote><span style=\"background-color: rgb(255, 255, 255);\">Nulla facilisi. Nullam eu scelerisque velit. Nunc convallis, justo nec feugiat ullamcorper, enim magna commodo felis, in eleifend tellus leo ac mauris. Etiam venenatis ut quam sit amet rhoncus. Donec ornare, leo at vestibulum convallis, augue dolor consectetur nisl, ac condimentum sem turpis sit amet sem. Curabitur metus lectus, fermentum et convallis a, ullamcorper in leo. Phasellus dictum, dui vitae feugiat malesuada,&nbsp;</span></blockquote><p><br></p><pre class=\"ql-syntax\" spellcheck=\"false\">function TextInputWithFocusButton() {\n  const inputEl = useRef(null);\n  const onButtonClick = () =&gt; {\n    // `current` points to the mounted text input element\n    inputEl.current.focus();\n  };\n  return (\n    &lt;&gt;\n      &lt;input ref={inputEl} type=\"text\" /&gt;\n      &lt;button onClick={onButtonClick}&gt;Focus the input&lt;/button&gt;\n    &lt;/&gt;\n  );\n}\n</pre><p><br></p><p><br></p>",
    "lbrph1fx": "<h1 class=\"ql-align-center\"><span class=\"ql-size-huge\" style=\"background-color: rgb(230, 0, 0);\">Lorem Ipsum</span></h1><p class=\"ql-align-center\"><br></p><p class=\"ql-align-center\"><br></p><h1><span style=\"background-color: rgb(255, 255, 255);\">Nullam fringilla ut ante a elementum. Suspendisse eu viverra erat. Praesent vehicula, lacus eget lobortis tincidunt, erat metus bibendum tellus, id consequat velit turpis non purus. Mauris molestie condimentum lacus ac semper. Nullam dictum nibh sed turpis rutrum, vel sagittis augue dapibus.</span></h1><p class=\"ql-align-center\"><br></p><p class=\"ql-align-center\"><br></p><p class=\"ql-align-center\"><br></p>",
    "lbrphexm": "<p class=\"ql-align-justify\"><br></p><p class=\"ql-align-justify\">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur purus justo, blandit et sapien vitae, cursus porta eros. Nullam efficitur leo nec lacus consectetur, a vulputate diam mattis. Ut sem est, sodales ut nisl id, tempus lobortis justo. Mauris vitae vestibulum justo. Pellentesque non odio sodales, sodales ante et, pretium eros. Quisque gravida sit amet eros ut lobortis. Nulla id condimentum ipsum. Fusce vitae odio sed erat rutrum rutrum ac eu dui. Donec porttitor dolor et venenatis molestie. Nullam eu metus tellus. Integer imperdiet pellentesque odio, id efficitur ex luctus nec. Mauris faucibus et turpis ac gravida.</p><p class=\"ql-align-justify\"><br></p><p class=\"ql-align-center\"><span style=\"background-color: rgb(255, 255, 255); color: rgb(102, 163, 224);\" class=\"ql-size-huge\">Aliquam condimentum sollicitudin magna</span></p><p class=\"ql-align-justify\"><br></p><p class=\"ql-align-justify\"><br></p><ul><li class=\"ql-align-justify\">Lorem ipsum dolor sit amet, consectetur adipiscing elit.</li><li class=\"ql-align-justify\">Aenean quis ligula tincidunt, fringilla est quis, vestibulum mauris.</li><li class=\"ql-align-justify\">Sed vel massa et tortor faucibus tincidunt ut nec dolor.</li><li class=\"ql-align-justify\">Morbi dapibus ex et lacus varius, dapibus mattis nisi volutpat.</li><li class=\"ql-align-justify\">Maecenas ac ex et arcu commodo egestas.</li><li class=\"ql-align-justify\">Fusce sed dolor tincidunt, efficitur nisi sed, varius mauris.</li></ul><p class=\"ql-align-justify\"><br></p><pre class=\"ql-syntax\" spellcheck=\"false\">def process_data(data):\n&nbsp; &nbsp; # Initialize variables\n&nbsp; &nbsp; sum = 0\n&nbsp; &nbsp; max_value = -float(\"inf\")\n&nbsp; &nbsp; min_value = float(\"inf\")\n\n&nbsp; &nbsp; # Iterate over the data\n&nbsp; &nbsp; for value in data:\n&nbsp; &nbsp; &nbsp; &nbsp; # Update the sum\n&nbsp; &nbsp; &nbsp; &nbsp; sum += value\n\n&nbsp; &nbsp; &nbsp; &nbsp; # Update the max value\n&nbsp; &nbsp; &nbsp; &nbsp; if value &gt; max_value:\n&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; max_value = value\n\n&nbsp; &nbsp; &nbsp; &nbsp; # Update the min value\n&nbsp; &nbsp; &nbsp; &nbsp; if value &lt; min_value:\n&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; min_value = value\n\n\n&nbsp; &nbsp; # Calculate the average\n&nbsp; &nbsp; average = sum / len(data)\n\n\n&nbsp; &nbsp; # Return the results\n&nbsp; &nbsp; return (sum, average, max_value, min_value)\n</pre><p> </p><p><br></p><p><span style=\"background-color: rgb(255, 255, 255);\" class=\"ql-size-large\">Malesuada auctor metus. Phasellus vel velit sit amet leo gravida vulputate consectetur quis ex. Praesent porta bibendum quam, sed molestie enim cursus eu. Sed eget ligula mi.</span></p><p><br></p><p><br></p><p class=\"ql-align-justify\"><br></p><p><br></p>",
}

export { samplenode, sampledb }
